name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # 15:00 CEST (summer), 14:00 CET (winter)

jobs:
  renovate:
    name: renovate
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v3.2.0
        with:
          private-key: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          client-id: ${{ vars.RENOVATE_APP_CLIENT_ID }}
          owner: ${{ github.repository_owner }}
          repositories: 'docker-compose,stacks'

      - name: Checkout
        uses: actions/checkout@v7
      - name: Run Renovate
        uses: renovatebot/github-action@v46.3.1
        with:
          token: ${{ steps.get_token.outputs.token }}
          configurationFile: ${{ github.workspace }}/config.js
        env:
          RENOVATE_DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
          RENOVATE_DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          RENOVATE_GHCR_USERNAME: ${{ vars.GHCR_USERNAME }}
          RENOVATE_GHCR_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
