name: renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # 15:00 CEST (summer), 14:00 CET (winter)

jobs:
  renovate:
    name: renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Run Renovate
        uses: renovatebot/github-action@v46.2.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          configurationFile: ${{ github.workspace }}/config.js
        env:
          RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
          RENOVATE_APP_PRIVATE_KEY: ${{ secrets.RENOVATE_APP_PRIVATE_KEY }}
          RENOVATE_USERNAME: ${{ vars.RENOVATE_BOT_USERNAME }}
          RENOVATE_AUTHOR: ${{ vars.RENOVATE_BOT_USERNAME }}
          RENOVATE_PRIVATE_EMAIL: ${{ vars.RENOVATE_BOT_EMAIL }}
          RENOVATE_DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }}
          RENOVATE_DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          RENOVATE_GHCR_USERNAME: ${{ vars.GHCR_USERNAME }}
          RENOVATE_GHCR_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_NTFY_URL: ${{ vars.NTFY_URL }}
          RENOVATE_NTFY_TOKEN: ${{ secrets.NTFY_TOKEN }}
